version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bhutan_postgres
    environment:
      POSTGRES_DB: bhutan_tourism
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bhutan_tourism"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: bhutan_app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/bhutan_tourism
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
    driver: local